### ISSUE TITLE
Need to save page edits twice in order to really save the changes.

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#387] opened 2018-09-20 09:54 UTC
After upgrading Piranha manager from 5.0.0 to 5.1.1 we need to click the green "Update" button twice when doing any page edits. If we click once, the changes just aren't saved, even though the site says that they were saved OK. We use a distributed cache based on Redis, but it all worked fine in 5.0.0.

We're probably the only one who encountered this, but do you maybe have any suggestions where we should look to resolve that based on your past experience? Maybe something went wrong during the migration? I didn't see anything related to this issue in 5.1.2, but maybe I'm wrong?

**Comment by tidyui** [comment] 2018-09-20 10:07
https://github.com/PiranhaCMS/piranha.core/wiki/Changelog

Version `5.1.2` has a fix in the HTML-editors for a bug that I think causes the exact problem you're describing. Test updating to the latest version and hopefully your problem will be fixed!

**Comment by mfronczyk** [comment] 2018-09-20 10:11
Great news! We'll try and close this if it fixes the problem.

**Comment by tidyui** [comment] 2018-09-24 11:49
Did updating to the latest version solve the problem?

**Comment by mfronczyk** [comment] 2018-09-24 12:55
Actually, we decided to wait until 5.2 with the upgrade. Do you think it's far away?

**Comment by tidyui** [comment] 2018-10-02 10:53
I have actually identified a bug still present for `MarkdownFields`, so it all depends what type of content you feel is not being updated. And we're closing in on the `5.2` release which will also include this fix of course.

**Comment by mfronczyk** [comment] 2018-10-02 11:13
Right, we noticed it when editing markdown fields.

**Comment by tidyui** [comment] 2018-10-02 12:31
This is now available in `5.2-beta1` which is available on NuGet together with a bunch of other stuff (https://github.com/PiranhaCMS/piranha.core/wiki/Pre-release-Changelog). Official release will hopefully be next week.

**Comment by tidyui** [comment] 2018-10-02 12:32
And I will close this as this is a duplicate of #392.

**Closed by tidyui** 2018-10-02 12:32 UTC
