### ISSUE TITLE
Piranha.AspNetCore dependency xsitemap is deprecated

### ISSUE THREAD

**Issue by jmbryan4** [PiranhaCMS/piranha.core#2092] opened 2024-09-09 15:56 UTC
![image](https://github.com/user-attachments/assets/7bec9f7e-7ab3-4f47-b06c-e2acabc2c522)
![image](https://github.com/user-attachments/assets/8a5e98ac-8e92-46f6-9c65-6b39f0adc7ac)

**Comment by tidyui** [comment] 2024-11-20 20:53
Duplicate of #2085

**Closed by tidyui** 2024-11-20 20:53 UTC
Labels: duplicate
