### ISSUE TITLE
Wrong permalink for non-default site

### ISSUE THREAD

**Issue by steelspace** [PiranhaCMS/piranha.core#441] opened 2018-11-22 11:14 UTC
I have created two sites, each dedicated to a specific language. I set culture and hostnames to both sites. The page is correctly loaded when entering the URL manually (with distinguishing URL part /EN /DE) but all links are missing that part.

**Comment by tidyui** [comment] 2018-11-22 15:14
Hostname is not part of the slug, and preview does not seem to take hostname into account when previewing, it assumes the permalink exists on the same site as the manager.

**Comment by steelspace** [comment] 2018-11-22 15:47
Makes sense that hostname is not part of the slug, so the bug is in generating the link. Is there a workaround at the moment (hook)?

**Comment by tidyui** [comment] 2018-11-24 06:43
Not at the moment, but we will probably do a `5.3.1` release with some fixes. Let's see if we can include a fix for this. I'm closing this issue as well as it is a duplicate of #335.

**Closed by tidyui** 2018-11-24 06:43 UTC
Labels: bug, core-manager
