### ISSUE TITLE
Can't remove tags after assigning one

### ISSUE THREAD

**Issue by flashvenom** [PiranhaCMS/piranha.core#1497] opened 2021-02-11 23:17 UTC
I have a bit of a usability/UI issue here. I'm using Firefox but this issue also persists in Chrome and I assume other browsers. When you assign a tag to a post, it's impossible to remove **all** tags and go back to having no tags in the field. This behavior can be repeated by simply assigning a tag. Then if you click the "x" on a tag, the drop down opens in the field and once you click off to anywhere else, hit tab, hit esc, etc - it assigns the first tag in the drop down.

I also tried just deleting the tag by using the text cursor, but once you delete all characters, the drop down appears again, and again once you take focus off of the field, it just automatically assigns the first tag in the drop down.  I also tried just deleting the tag so the drop down is active, and hitting Publish, but hitting that button puts the DOM input focus on the button, thereby triggering the (what I believe to be) OnFocusOut behavior of the tag field which then assigns whatever tag is selected in the auto-fill/suggestion drop down.

So I effectively have to assign some sort of tag. My installation, especially the manager, is pretty vanilla, so I don't think this is an issue with my code.
![image](https://user-images.githubusercontent.com/6750623/107710405-b6e26680-6c7b-11eb-976b-aef1fea0e8e6.png)

**Comment by jensbrak** [comment] 2021-02-12 07:00
Tried this on my 9.0-rc1 install and I seem to be able to remove all tags.
The behaviour you describe is identical here up to the point where you remove the tag. Yes, the list of tags is opened but once I click somewhere to leave the tag field - the list is closed and the field is left empty. No assignment. 

Am I missing something here?

**Comment by tidyui** [comment] 2021-02-12 07:33
Duplicate of #1411. Fixed in `master` and will be released in `9.0`!

**Closed** 2021-02-12 07:33 UTC
Labels: duplicate
