### ISSUE TITLE
Sitemap not following IsHidden

### ISSUE THREAD

**Issue by saefren** [PiranhaCMS/piranha.core#1256] opened 2020-06-27 17:04 UTC
First of all; **very nice CMS**. I have used the legacy version in the past and I am very happy you've switch to dotnet core!

![image](https://user-images.githubusercontent.com/16624717/85927719-3156a580-b8a8-11ea-9b20-3a6b4182a075.png)

It seems the IsHidden property is ignored when generating the sitemap. I don't see any reference to it in the middleware:

https://github.com/PiranhaCMS/piranha.core/blob/66051cd940c496a2ee0ffe01e1cf9a7b844be2af/core/Piranha.AspNetCore/SitemapMiddleware.cs
Is this intentional? I am confused.

Thanks & regards!

**Comment by tidyui** [comment] 2020-06-28 19:36
Hi there! This is a duplicate of #1000 which we are planning on fixing for 8.4. Please take a look at the referenced issue an join in on the discussion if you have some other input on it!

Best regards

**Closed by tidyui** 2020-06-28 19:36 UTC
Labels: duplicate
