### ISSUE TITLE
Column Block - Change Add/Insert Image to Media - Enhancement 

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core#549] opened 2019-03-27 23:01 UTC
Feature request..

When you add a Column block, you can add/insert an image in the column.

It would be nice if this could be changed to 'add/insert media' or add an additional button to the column edit for 'add/insert video'.

The 'select media' dialog shows MP4 and images, but the tags in the view need to be expanded to support video.

**Comment by tidyui** [comment] 2019-03-27 23:04
Hi there! Closing as this is a duplicate of #459

Regards

**Closed by tidyui** 2019-03-27 23:04 UTC
