### ISSUE TITLE
IList Region - PageField

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#693] opened 2019-07-01 14:50 UTC
Hi

I don't know if someone's reported this, could be a possible duplicate.

When you have an `IList<MyClass>` region containing multiple fields, they don't get properly assigned after choosing the page from provided list.

![2019-07-01 15_48_03-Window](https://user-images.githubusercontent.com/32654709/60445712-a94baa80-9c17-11e9-9df8-ddedb72ddab6.png)

In the image above - the second link became empty, replacing an existing one (first).

BR
Chris

**Comment by aneff-official** [comment] 2019-07-01 15:04
P.S. Is there a way to assign the `.Value` of an **HtmlField** for a `ListTitle` or somehow to strip the Html tags?

![2019-07-01 16_03_11-Window](https://user-images.githubusercontent.com/32654709/60446746-ea44be80-9c19-11e9-986a-b99ffd05eadc.png)

**Comment by tidyui** [comment] 2019-07-03 22:05
Hi there! If you have the time, would you mind testing this bug on the 7.0 manager?

**Comment by aneff-official** [comment] 2019-07-05 08:15
Hi there

I can't really get the alpha version working for some reason and I think this is where the problem lies:
`config.ModelBinderProviders.Insert(0, new Piranha.Manager.Binders.AbstractModelBinderProvider());`

Chris

**Comment by tidyui** [comment] 2019-07-05 08:21
Hi! The startup is different for `7.0` as models are no longer passed as form data (where the `ModelBinders` is used), it is passed as JSON instead from `Vue.js`. The MVC startup in `alpha1` looks like this:

    services.AddLocalization(options =>
        options.ResourcesPath = "Resources"
    );
    services.AddMvc()
        .AddRazorPagesOptions(options => {
            options.Conventions.AuthorizeAreaFolder("Manager", "/");
            options.Conventions.AllowAnonymousToAreaPage("Manager", "/login");
        })
        .AddViewLocalization()
        .AddDataAnnotationsLocalization()
        .Addjsgnoptions(options =>
        {
            options.SerializerSettings.TypeNameHandling = TypeNameHandling.Auto;
        })
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

This will be simplify with an extension method for the final release.

**Comment by aneff-official** [comment] 2019-07-05 09:31
Hi

Just tested the alpha and here is what I found.

### Observations

- First things first - I have to say that it all looks way better now, I am still getting used to the new view 😄

![2019-07-05 09_52_43-Login](https://user-images.githubusercontent.com/32654709/60712944-fd080d80-9f0f-11e9-98ba-f09e9a55b19e.png)

- Your piece of code worked - I just copy+pasted it and it worked like a charm. After running the website, I pressed on `Seed` after which I have added some values to the `Site` (Culture). I have stopped debugging, added custom region, with `Piranha` fields (**PageField** instead of **PageInfoField**) and when I tried to run the application I had the following error:

![2019-07-05 10_17_33-Internal Server Error](https://user-images.githubusercontent.com/32654709/60712961-05f8df00-9f10-11e9-8d21-e1ee9756a5d8.png)

- Because the `var site` was null - although **WebApp.Site** had a value and properties, it was failing to assign value to the variable for some reason.

![2019-07-05 10_21_49-Edit page](https://user-images.githubusercontent.com/32654709/60712985-114c0a80-9f10-11e9-8fa5-f4b7bca04800.png)

- I could get to the `manager/` though, but then again, my region was there, but I was not able to add anything. Pressing the "+" button wouldn't work.

Cheers,
Chris

**Comment by tidyui** [comment] 2019-07-05 10:13
Hi again, how is site assigned since you say WebApp.Site is assigned? And when adding a new region, can you check your browser network tab to see what error is returned from the api endpoint responsible for this.

Best regards

**Comment by aneff-official** [comment] 2019-07-05 12:10
Hi

What I meant is, that `site` is null (can't get the content) but **WebApp.Site** loads data properly.

![2019-07-05 13_06_47-Seven (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/32654709/60721523-2a5fb600-9f26-11e9-94bb-155abcc5e990.png)

There is the Error (500) in Network tab when trying to add an item

![2019-07-05 13_08_04-Edit page](https://user-images.githubusercontent.com/32654709/60721531-2f246a00-9f26-11e9-8f3d-72f84788fc3a.png)

BR,
Chris

**Comment by tidyui** [comment] 2019-07-05 14:50
Ok, thank! A couple of more questions 😀

1. Have you create a new project from the BlogTemplate so I can try to reproduce it on my end.
2. Can you take a look at the `Response` tab for the 500 response. Maybe the exception details is included.

Regards

**Comment by tidyui** [comment] 2019-07-05 15:07
I just created a new project from the current templates with `dotnet new piranha.blog`, updated all references to `7.0.0-alpha1` and the modified the startup code as mentioned above and everything worked as expected. I also tried to create a simple region containing a `StringField` and a `PageField` and everything works as expected (see attached screenshot). One thing that puzzles me from your screenshot is that it **looks like** your region only has one field in it. If this is the case, custom objects containing a single field is **not supported**, see this documentation article as reference:

http://piranhacms.org/docs/basics/how-to-setup-content

<img width="1353" alt="Skärmavbild 2019-07-05 kl  17 04 24" src="https://user-images.githubusercontent.com/781266/60731212-517aaf80-9f47-11e9-81e9-02426fc21e41.png">


Best regards

**Comment by aneff-official** [comment] 2019-07-08 09:45
![2019-07-08 09_27_03-Window](https://user-images.githubusercontent.com/32654709/60800603-659ff600-a16d-11e9-97e5-33af83512742.png)
![2019-07-08 10_36_06-Window](https://user-images.githubusercontent.com/32654709/60800604-659ff600-a16d-11e9-8ee7-7e69a0a52156.png)

**Comment by aneff-official** [comment] 2019-07-08 09:56
Hi there

Sorry for the late response, I was on holiday.

### Things done:

- Did `piranha.blog` and updated to `alpha`
- The region has a **StringField** and a **PageField** (2 in total)
- The images above show my custom class (**1**) and the **HTML** file from 
Manager View -> Dev Tools -> Error Response

P.S. Are you able to provisionally say when the new release is coming out? Thanks.

BR
Chris

**Comment by aneff-official** [comment] 2019-07-15 07:31
Is this going to be addressed in the new release?

**Comment by tidyui** [comment] 2019-07-15 08:53
Hi, since I can't reproduce the error see the above commit. I have added your Href region into the `MvcWeb` example on the `TeaserPage` which is used on the start page. Get the latest source code for the repo and compare if there's any differences between your implementation.

**Comment by aneff-official** [comment] 2019-07-15 14:39
I've just tested it, got `alpha-2` version and it seems that whatever code it uses, fixes the problem.

BTW - I noticed that the **Preview** option (under Save) on the Home page doesn't work.

**Comment by tidyui** [comment] 2019-07-15 17:16
Great, I'll close this issue then! The preview button isn't implemented yet!

**Closed by tidyui** 2019-07-15 17:16 UTC
Labels: bug
