### ISSUE TITLE
Duplicated slug --> uncaught exception

### ISSUE THREAD

**Issue by LukeOwlclaw** [PiranhaCMS/piranha.core#1387] opened 2020-10-30 20:39 UTC
I just ran Piranha for the first time and immediately stumbled upon following error:

Run MvcWeb and create new standard page, set slug to "home". When clicking the save button, the spinner keeps spinning.

Problem: Call to http://localhost:5000/manager/api/page/save/draft returns with error code 500. The corresponding stacktrace:

    Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
     ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Piranha_Pages.SiteId, Piranha_Pages.Slug'.
       at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
       at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
       at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
       at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
       at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)

**Comment by tidyui** [comment] 2020-10-30 20:50
This is a duplicate of #1369 which will be fixed in 9.0. This check was missed when the manager interface was rewritten from pure MVC to Razor Pages/Vue.js

**Closed by tidyui** 2020-10-30 20:50 UTC
Labels: duplicate
