### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by airfanBG** [PiranhaCMS/piranha.core#1473] opened 2021-01-13 21:43 UTC
Hi! I have a strange problem with login. When I run my project in debug I can login with "admin" and "password". When I deploy my project to IIS and try the same login it returns me to url "/manager/login?ReturnUrl=%2Fmanager". I run my project with SQL server.Where is the problem. Greetings!

**Comment by tidyui** [comment] 2021-01-14 08:31
Duplicate of #1472

**Closed by tidyui** 2021-01-14 08:31 UTC
Labels: duplicate
