### ISSUE TITLE
Sitemap.xml shows incorrect domain when behind Azure Application Gateway

### ISSUE THREAD

**Issue by EddyCwdry** [PiranhaCMS/piranha.core#1674] opened 2021-07-28 04:51 UTC
Due to the way the Azure Application Gateway works, the host provided in the request header will always be _appname_.azurewebsites.net , meaning that the generated sitemap.xml will have the incorrect domain used on the output.

The root cause appears to be this line https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/SitemapMiddleware.cs#L54 

Is there an existing workaround for scenarios where the host is not able to be provided via the request header?

**Comment by tidyui** [comment] 2021-07-28 07:08
This is a duplicate of #1608, I’ll respond in that issue!

**Closed by tidyui** 2021-07-28 07:08 UTC
