### ISSUE TITLE
Custom authorize

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core#1077] opened 2020-03-02 19:58 UTC
I have my own controller, which works, I get everything I want.
But when I add Authorize decorator to it, I am never taken back once I login.

**Comment by tidyui** [comment] 2020-03-03 12:16
Are we talking in the public application of the manager area?

**Comment by traustitj** [comment] 2020-03-03 12:31
I want to have some pages require login to see your specific page, like order status or something like that. They should not have to go to the manager area at all.
Just one page with a form to login, next they see their page.

Best to be able to not re-invent anything here, which is also the reason I picked Piranha cms, it looks like it has everything I just need to learn this, quickly. Unfortunately there isn't much information out there.

**Comment by tidyui** [comment] 2020-03-03 12:32
Then I'm closing this issue as the information is a duplicate of issue #1076

**Closed by tidyui** 2020-03-03 12:32 UTC
Labels: question
