### ISSUE TITLE
TinyMCE always highlighting italic

### ISSUE THREAD

**Issue by pauldbentley** [PiranhaCMS/piranha.core#790] opened 2019-09-04 16:59 UTC
There is a certain situation where TinyMCE is always highlighting the Italic button in the toobar even when the content isn't Italic.

Steps to reproduce:

1. Create a `Page` with a `Region` and set the `Display` property set to `RegionDisplayMode.Content`
2. Add a content block and enter some content
3. Save the page
4. Reload the browser
5. Click into the content to activate the toolbar
6. The Italic button is highlighted

An example of this can be found in the `MvcWeb` example `TeasterPage` class.

If you have multiple content blocks, this only happens on the **1st** content block you click in.

This doesn't happen if there are no regions or the region is not set to `RegionDisplayMode.Content`.  I'm only guessing but maybe somewhere in the Vuejs when rendering the regions an `<i>` tag is being returned unclosed which is making TinyMCE think the content is Italic?

**Comment by tidyui** [comment] 2019-09-06 04:21
We'll try to see if we can reproduce this!

**Comment by tidyui** [comment] 2019-12-08 12:25
Hi there @pauldbentley Have this issue persisted? I haven't really been able to reproduce it. What web browser are you using?

**Comment by pauldbentley** [comment] 2019-12-09 10:15
Yes this is will an issue.  I can reproduce in Chrome, but it works fine in Edge.

This example is from the `MvcWeb` example `TeasterPage` class.

![TinyMce-Italic](https://user-images.githubusercontent.com/5243982/70427365-7d590e80-1a6c-11ea-8e71-2a70eb3e80f1.gif)

Its only when you press F5 to reload the page so not a big issue but it happens to me a few times when editing sites.

**Comment by tidyui** [comment] 2020-05-16 06:19
I have narrowed it down to the issue appearing in Chrome, I usually use Firefox or Safari. Problem is the issue is most likely in the TinyMCE editor (https://tiny.cloud). I've tried updating to the latest version as of date (5.2.2) but the issue seems to persist.

Maybe it would be better to open an issue at Tiny?

**Comment by tidyui** [comment] 2022-06-08 06:29
Closing as this was an issue related to a third-party component

**Closed by tidyui** 2022-06-08 06:29 UTC
