### ISSUE TITLE
After upgrade to version 7xx new pages are not rendering blocks.

### ISSUE THREAD

**Issue by AndersonFetter** [PiranhaCMS/piranha.core#875] opened 2019-10-23 02:18 UTC
Hello guys,

First of all, I love Piranha CMS. 

I'm implementing a new website. I started before release 7. After upgrade to release 7.xx when I create a new page the current views are not able to render blocks. Aparent there is a new way to render blocks. 

This is an old view I have on the project I just created a new page on my web site.

Am I doing something wrong or i missed some part of the upgrade?

View:

```
<div class="main mt-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 page-body">
                <div class="container">
                    @Html.DisplayFor(m => m.Blocks)
                </div>
            </div>
        </div>
    </div>
</div>
``` 

![image](https://user-images.githubusercontent.com/9358898/67350709-3cc63400-f597-11e9-9b3e-6966111357df.png)

**Comment by tidyui** [comment] 2019-10-23 07:20
Hi there! Nothing has changed in the client model in regards to blocks between `6.x` and `7.0`. When you send a collection to `@Html.DisplayFor(...)` it should enumerate the items, not send the actual collection to a display template. Have you upgrade anything else in your project?

Best regards

**Comment by tidyui** [comment] 2019-11-01 09:39
Did you solve this issue. Please come back with more information or we will close the issue.

Best regards

**Comment by afetter** [comment] 2019-11-02 03:41
I found the issue, but I don't know how to fix it.

This is the page I have been created a while and is working.
![image](https://user-images.githubusercontent.com/5475228/68065476-d9e65100-fd7d-11e9-8fb1-d2a63551af21.png)

and this is the same page type, but I created just now and is not working.

![image](https://user-images.githubusercontent.com/5475228/68065485-f5515c00-fd7d-11e9-99b2-c61f2989d1fc.png)

If I add new content on the old pages I get the same error. The problem is on the Block. The old content is **Piranha.Extend.Blocks.HtmlColumnBlock** and the new one is **Piranha.Extend.Blocks.ColumnBlock.**

Do you have any idea to fix it?

**Comment by tidyui** [comment] 2019-11-02 06:50
Thanks! Since you’ve upgraded your project you’re simply missing the DisplayTemplate for the new ColumnBlock. DisplayTemplatrs are not a part of the core packages but are provided by the templates when you create a new project. You can find the display template in the template project here:

https://github.com/PiranhaCMS/piranha.core.templates/blob/master/web/mvc/Views/Cms/DisplayTemplates/ColumnBlock.cshtml

Best regards

**Comment by afetter** [comment] 2019-11-02 09:22
Thank you so much mate.

**Closed** 2019-11-02 14:03 UTC
Labels: question
