### ISSUE TITLE
BUG? Model.Archive.Category - NULL

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#670] opened 2019-06-13 16:10 UTC
Hi there,

I will try to be quick for this one.

So I think that when I go to the URL:
`localhost:5000/myArchive/category/special/`
I should be getting the category as well in
`@Model.Archive.Category`, but because this is null, so are the Slug&Title.

By looking at that:

![2019-06-13 16_02_31-HoltDoctors (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/32654709/59448851-ec2b1700-8dfd-11e9-8f6b-e00f063c8a54.png)
![2019-06-13 16_02_49-HoltDoctors (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/32654709/59448855-ec2b1700-8dfd-11e9-8a78-c3c377b3008c.png)

I think that they have to be there, but are not set? Is this something not implemented, a weird bug or just me not understanding how it works? Because the posts in that archive have their `category` set + you can get all the categories with `await api.Posts.GetAllCategoriesAsync(Id)`.

The whole point of this is to be able to get the current *category* that we have have in the URL in our Model, so I can use it.

Regards,
Chris

**Comment by filipjansson** [comment] 2019-06-13 17:44
Hi!

It looks like you are right.
I see the same issue in the `version/6.1` branch.
But it looks like this issue is fixed in `master` branch, which is currently in development for the 7.0 release.

BR
Filip

**Comment by tidyui** [comment] 2019-06-13 19:16
Hi! I can confirm that this bug was introduced in 6.0 and has been fixed in master. The workaround is to manually load the category and set the values in the model.

Regards

**Comment by tidyui** [comment] 2019-06-13 19:18
Duplicate of #620

**Comment by aneff-official** [comment] 2019-06-14 11:19
Alright, thank you! I sorted this out.

Although this might be off topic, is there any particular reason that this code returns "-1"?:

```
// Get current post and all posts
var posts = await api.Posts.GetAllAsync(blogId);
var currentPost = await api.Posts.GetByIdAsync(Model.Id);

// Get current post index
var postsList = posts.ToList();
var index = postsList.IndexOf(currentPost);

// index = -1;
```

BR
Chris

**Comment by aneff-official** [comment] 2019-06-14 11:41
Hi again,

**EDIT:**
I don't know the reason behind this, but using the following code fixed it:
```
var posts = await api.Posts.GetAllAsync<Piranha.Models.PostInfo>(blogId);
```

I guess that `PostInfo` type is properly enumerated and `DynamicPost` could use the same approach to get `IndexOf` working?

Chris

**Comment by tidyui** [comment] 2019-06-14 11:45
`DynamicPosts` are never cached, meaning that each time you request them a new object instance will be created. Calling `IndexOf` on a generic list will only compare the actual pointers of the object, and since they are unique instance the index should be `-1`. The reason why it works with `PostInfo` is that this model type is cached, so both requests are in fact returning the same instance of the post.

Best regattas

**Comment by tidyui** [comment] 2019-07-29 03:44
Closing as this is fixed in master

**Closed by tidyui** 2019-07-29 03:44 UTC
Labels: duplicate
